type Book {
    id: Int!
    title: String!
    author: Author!
    year: Int
}

type Author {
    id: Int!
    name: String!
}

type Query {
    getBooks(): [Book]
    getAuthors(): [Author]
    getBook(id: Int!): Book
    searchBooks(title: String, author: String): [Book]
}

input BookInput {
    title: String
    author: Author
    year: Int
}

input AuthorInput {
    name: String
}

type Mutation {
    addBook(input: BookInput): Book
    updateBook(id: Int!, input: BookInput): Book
    addAuthor(input: AuthorInput): Author
    updateAuthor(id: Int!, input: AuthorInput): Author
}

schema {
    query: BookQuery
    mutation: BookMutation
}
