type Book {
    id: Int!
    title: String!
    year: Int!
    authors: [Author!]!
}

type Author {
    id: Int!
    name: String!
    books: [Book!]
}

type Query {
    getBooks(): [Book]
    getAuthors(): [Author]
    getBookById(id: Int!): Book
    getAuthorById(id: Int!): Author
    searchBooks(title: String, author: Int, year: Int): [Book]
}

input BookInput {
    title: String
    year: Int
    authors: [Int!]!
}

input AuthorInput {
    name: String!
}

type Mutation {
    addBook(input: BookInput): Book
    updateBook(id: Int!, input: BookInput): Book
    addAuthor(input: AuthorInput): Author
    updateAuthor(id: Int!, input: AuthorInput): Author
}

schema {
    query: Query
    mutation: Mutation
}
